// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_send.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message_send.proto

It has these top-level messages:
	MessageSend
*/
package pb

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

var messageSend MessageSend

// 消息发送 type:3
type MessageSend struct {
	DeviceId     uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceType   uint32 `protobuf:"varint,2,opt,name=device_type,json=deviceType" json:"device_type,omitempty"`
	Sender       uint64 `protobuf:"varint,3,opt,name=sender" json:"sender,omitempty"`
	Sign         uint64 `protobuf:"varint,4,opt,name=sign" json:"sign,omitempty"`
	ReceiverType uint32 `protobuf:"varint,5,opt,name=receiver_type,json=receiverType" json:"receiver_type,omitempty"`
	Receiver     uint64 `protobuf:"varint,6,opt,name=receiver" json:"receiver,omitempty"`
	Type         uint32 `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	Content      string `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
}

func (m *MessageSend) Reset()                    { *m = MessageSend{} }
func (m *MessageSend) String() string            { return proto.CompactTextString(m) }
func (*MessageSend) ProtoMessage()               {}
func (*MessageSend) Descriptor() ([]byte, []int) { return messageSend.fileDescriptor(), []int{0} }

func (m *MessageSend) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MessageSend) GetDeviceType() uint32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *MessageSend) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *MessageSend) GetSign() uint64 {
	if m != nil {
		return m.Sign
	}
	return 0
}

func (m *MessageSend) GetReceiverType() uint32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageSend) GetReceiver() uint64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MessageSend) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageSend) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageSend)(nil), "pb.MessageSend")
}

func init() { proto.RegisterFile("message_send.proto", messageSend.fileDescriptor()) }

func (MessageSend) fileDescriptor() []byte {
	return []byte{
		// 197 bytes of a gzipped FileDescriptorProto
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x3d, 0x6e, 0x84, 0x30,
		0x10, 0x85, 0x65, 0x42, 0xf8, 0x19, 0x42, 0x33, 0x45, 0x64, 0x25, 0x45, 0x50, 0xd2, 0x50, 0xa5,
		0xc9, 0x29, 0x52, 0xa4, 0x21, 0xdb, 0xa3, 0x05, 0x8f, 0x90, 0x8b, 0x35, 0x96, 0x6d, 0x21, 0x71,
		0xe1, 0x3d, 0xc7, 0x8a, 0x31, 0xee, 0xe6, 0x7d, 0x4f, 0xef, 0x93, 0x0d, 0x78, 0x23, 0xef, 0xaf,
		0x0b, 0x8d, 0x9e, 0x8c, 0xfa, 0xb6, 0x6e, 0x0d, 0x2b, 0x66, 0x76, 0xfa, 0xbc, 0x0b, 0x68, 0xfe,
		0x62, 0xf5, 0x4f, 0x46, 0xe1, 0x3b, 0xd4, 0x8a, 0x36, 0x3d, 0xd3, 0xa8, 0x95, 0x14, 0x9d, 0xe8,
		0xf3, 0xa1, 0x8a, 0xe0, 0x57, 0xe1, 0x07, 0x34, 0x67, 0x19, 0x76, 0x4b, 0x32, 0xeb, 0x44, 0xdf,
		0x0e, 0x10, 0xd1, 0x65, 0xb7, 0x84, 0xaf, 0x50, 0x1c, 0x7e, 0x72, 0xf2, 0x89, 0xa7, 0x67, 0x42,
		0x84, 0xdc, 0xeb, 0xc5, 0xc8, 0x9c, 0x29, 0xdf, 0xf8, 0x05, 0xad, 0xa3, 0x99, 0xf4, 0x46, 0x2e,
		0xea, 0x9e, 0x59, 0xf7, 0x92, 0x20, 0x0b, 0xdf, 0xa0, 0x4a, 0x59, 0x16, 0xf1, 0x35, 0x29, 0x1f,
		0x52, 0xde, 0x95, 0xbc, 0xe3, 0x1b, 0x25, 0x94, 0xf3, 0x6a, 0x02, 0x99, 0x20, 0xab, 0x4e, 0xf4,
		0xf5, 0x90, 0xe2, 0x54, 0xf0, 0x9f, 0x7f, 0x1e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0x01, 0x84,
		0x7c, 0x09, 0x01, 0x00, 0x00,
	}
}
