// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_ack.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message_ack.proto

It has these top-level messages:
	MessageACK
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 投递消息回执
type MessageACK struct {
	SyncSequence int64 `protobuf:"varint,1,opt,name=sync_sequence,json=syncSequence" json:"sync_sequence,omitempty"`
}

func (m *MessageACK) Reset()                    { *m = MessageACK{} }
func (m *MessageACK) String() string            { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()               {}
func (*MessageACK) Descriptor() ([]byte, []int) { return messageACKFileDescriptor, []int{0} }

func (m *MessageACK) GetSyncSequence() int64 {
	if m != nil {
		return m.SyncSequence
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
}

func init() { proto.RegisterFile("message_ack.proto", messageACKFileDescriptor) }

var messageACKFileDescriptor = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0x32, 0xe4, 0xe2, 0xf2, 0x85, 0x48, 0x38, 0x3a, 0x7b, 0x0b, 0x29, 0x73, 0xf1, 0x16,
	0x57, 0xe6, 0x25, 0xc7, 0x17, 0xa7, 0x16, 0x96, 0xa6, 0xe6, 0x25, 0xa7, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x30, 0x07, 0xf1, 0x80, 0x04, 0x83, 0xa1, 0x62, 0x49, 0x6c, 0x60, 0xdd, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xed, 0xcf, 0x51, 0xce, 0x52, 0x00, 0x00, 0x00,
}
