// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	MessageItem
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息投递
type Message struct {
	Messages []*MessageItem `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return messageFileDescriptor, []int{0} }

func (m *Message) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 单条消息投递
type MessageItem struct {
	SenderType   int32  `protobuf:"varint,1,opt,name=sender_type,json=senderType" json:"sender_type,omitempty"`
	SenderId     uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	DeviceId     uint64 `protobuf:"varint,3,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	ReceiverType uint64 `protobuf:"varint,5,opt,name=receiver_type,json=receiverType" json:"receiver_type,omitempty"`
	ReceiverId   uint64 `protobuf:"varint,6,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Type         uint32 `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	Content      string `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
	Sequence     uint64 `protobuf:"varint,9,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *MessageItem) Reset()                    { *m = MessageItem{} }
func (m *MessageItem) String() string            { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()               {}
func (*MessageItem) Descriptor() ([]byte, []int) { return messageFileDescriptor, []int{1} }

func (m *MessageItem) GetSenderType() int32 {
	if m != nil {
		return m.SenderType
	}
	return 0
}

func (m *MessageItem) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MessageItem) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MessageItem) GetReceiverType() uint64 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageItem) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageItem) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageItem) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageItem)(nil), "pb.MessageItem")
}

func init() { proto.RegisterFile("message.proto", messageFileDescriptor) }

var messageFileDescriptor = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3d, 0x6b, 0xc3, 0x30,
	0x10, 0x86, 0x51, 0xbe, 0x6c, 0x9f, 0x6b, 0x0a, 0x37, 0x89, 0x76, 0x88, 0x48, 0x17, 0x41, 0xc1,
	0x43, 0x0b, 0xfd, 0x0f, 0x1e, 0xba, 0x88, 0xee, 0xa5, 0x96, 0x8e, 0xa2, 0x21, 0xb2, 0x6a, 0xa9,
	0x81, 0xfc, 0xf3, 0x8e, 0x25, 0x92, 0x15, 0xb2, 0xdd, 0x3d, 0xef, 0xa3, 0x17, 0x71, 0xd0, 0x1d,
	0x29, 0x84, 0xaf, 0x6f, 0xea, 0xfd, 0x3c, 0xc5, 0x09, 0x57, 0x7e, 0x3c, 0xbc, 0x41, 0xf5, 0x9e,
	0x21, 0x3e, 0x43, 0xbd, 0x8c, 0x81, 0x33, 0xb1, 0x96, 0xed, 0xcb, 0x7d, 0xef, 0xc7, 0x7e, 0x61,
	0x43, 0xa4, 0xa3, 0xba, 0x0a, 0x87, 0x3f, 0x06, 0xed, 0x4d, 0x82, 0x7b, 0x68, 0x03, 0x39, 0x43,
	0xf3, 0x67, 0x3c, 0x7b, 0xe2, 0x4c, 0x30, 0xb9, 0x55, 0x90, 0xd1, 0xc7, 0xd9, 0x13, 0x3e, 0x42,
	0xb3, 0x08, 0xd6, 0xf0, 0x95, 0x60, 0x72, 0xa3, 0xea, 0x0c, 0x06, 0x73, 0x09, 0x0d, 0x9d, 0xac,
	0xa6, 0x4b, 0xb8, 0xce, 0x61, 0x06, 0x83, 0xc1, 0x27, 0xe8, 0x66, 0xd2, 0x64, 0x4f, 0xa5, 0x7c,
	0x9b, 0x84, 0xbb, 0x02, 0x53, 0xfd, 0x1e, 0xda, 0xab, 0x64, 0x0d, 0xdf, 0x25, 0x05, 0x0a, 0x1a,
	0x0c, 0x22, 0x6c, 0xd2, 0xe3, 0x4a, 0x30, 0xd9, 0xa9, 0x34, 0x23, 0x87, 0x4a, 0x4f, 0x2e, 0x92,
	0x8b, 0xbc, 0x16, 0x4c, 0x36, 0xaa, 0xac, 0xf8, 0x00, 0x75, 0xa0, 0x9f, 0x5f, 0x72, 0x9a, 0x78,
	0x53, 0x3e, 0x9b, 0xf7, 0x71, 0x97, 0xae, 0xf7, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x54, 0x31,
	0xea, 0x39, 0x4e, 0x01, 0x00, 0x00,
}
