// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_send.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message_send.proto

It has these top-level messages:
	MessageSend
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息发送
type MessageSend struct {
	ReceiverType int32  `protobuf:"varint,1,opt,name=receiver_type,json=receiverType" json:"receiver_type,omitempty"`
	ReceiverId   uint64 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Type         int32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Content      string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Sequence     uint64 `protobuf:"varint,5,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *MessageSend) Reset()                    { *m = MessageSend{} }
func (m *MessageSend) String() string            { return proto.CompactTextString(m) }
func (*MessageSend) ProtoMessage()               {}
func (*MessageSend) Descriptor() ([]byte, []int) { return messageSendFileDescriptor, []int{0} }

func (m *MessageSend) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageSend) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageSend) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageSend) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageSend) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageSend)(nil), "pb.MessageSend")
}

func init() { proto.RegisterFile("message_send.proto", messageSendFileDescriptor) }

var messageSendFileDescriptor = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x2f, 0x4e, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0x9a, 0xcb, 0xc8, 0xc5, 0xed, 0x0b, 0x91, 0x0a, 0x4e, 0xcd, 0x4b, 0x11, 0x52,
	0xe6, 0xe2, 0x2d, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x2d, 0x8a, 0x2f, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0xe2, 0x81, 0x09, 0x86, 0x54, 0x16, 0xa4, 0x0a, 0xc9, 0x73,
	0x71, 0xc3, 0x15, 0x65, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x04, 0x71, 0xc1, 0x84, 0x3c,
	0x53, 0x84, 0x84, 0xb8, 0x58, 0xc0, 0x9a, 0x99, 0xc1, 0x9a, 0xc1, 0x6c, 0x21, 0x09, 0x2e, 0xf6,
	0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57,
	0x48, 0x8a, 0x8b, 0xa3, 0x38, 0xb5, 0xb0, 0x34, 0x35, 0x2f, 0x39, 0x55, 0x82, 0x15, 0x6c, 0x16,
	0x9c, 0x9f, 0xc4, 0x06, 0x76, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xad, 0xa3, 0xb4,
	0xc0, 0x00, 0x00, 0x00,
}
