// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sync_trigger.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sync_trigger.proto

It has these top-level messages:
	SyncTrigger
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 同步消息触发
type SyncTrigger struct {
	IsNewDevice bool   `protobuf:"varint,1,opt,name=is_new_device,json=isNewDevice" json:"is_new_device,omitempty"`
	Sequence    uint64 `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *SyncTrigger) Reset()                    { *m = SyncTrigger{} }
func (m *SyncTrigger) String() string            { return proto.CompactTextString(m) }
func (*SyncTrigger) ProtoMessage()               {}
func (*SyncTrigger) Descriptor() ([]byte, []int) { return SyncTriggerFileDescriptor, []int{0} }

func (m *SyncTrigger) GetIsNewDevice() bool {
	if m != nil {
		return m.IsNewDevice
	}
	return false
}

func (m *SyncTrigger) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncTrigger)(nil), "pb.SyncTrigger")
}

func init() { proto.RegisterFile("sync_trigger.proto", SyncTriggerFileDescriptor) }

var SyncTriggerFileDescriptor = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xae, 0xcc, 0x4b,
	0x8e, 0x2f, 0x29, 0xca, 0x4c, 0x4f, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0xf2, 0xe5, 0xe2, 0x0e, 0xae, 0xcc, 0x4b, 0x0e, 0x81, 0x48, 0x08, 0x29, 0x71,
	0xf1, 0x66, 0x16, 0xc7, 0xe7, 0xa5, 0x96, 0xc7, 0xa7, 0xa4, 0x96, 0x65, 0x26, 0xa7, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x04, 0x71, 0x67, 0x16, 0xfb, 0xa5, 0x96, 0xbb, 0x80, 0x85, 0x84, 0xa4,
	0xb8, 0x38, 0x8a, 0x53, 0x0b, 0x4b, 0x53, 0xf3, 0x92, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58,
	0x82, 0xe0, 0xfc, 0x24, 0x36, 0xb0, 0xc9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x45,
	0x54, 0x8e, 0x6f, 0x00, 0x00, 0x00,
}
