// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_send.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message_send.proto

It has these top-level messages:
	MessageSend
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息发送 type:5
type MessageSend struct {
	DeviceId     uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceType   uint32 `protobuf:"varint,2,opt,name=device_type,json=deviceType" json:"device_type,omitempty"`
	Sender       uint64 `protobuf:"varint,3,opt,name=sender" json:"sender,omitempty"`
	Sign         uint64 `protobuf:"varint,4,opt,name=sign" json:"sign,omitempty"`
	ReceiverType uint32 `protobuf:"varint,5,opt,name=receiver_type,json=receiverType" json:"receiver_type,omitempty"`
	Receiver     uint64 `protobuf:"varint,6,opt,name=receiver" json:"receiver,omitempty"`
	Type         uint32 `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	Content      []byte `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *MessageSend) Reset()                    { *m = MessageSend{} }
func (m *MessageSend) String() string            { return proto.CompactTextString(m) }
func (*MessageSend) ProtoMessage()               {}
func (*MessageSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageSend) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MessageSend) GetDeviceType() uint32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *MessageSend) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *MessageSend) GetSign() uint64 {
	if m != nil {
		return m.Sign
	}
	return 0
}

func (m *MessageSend) GetReceiverType() uint32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageSend) GetReceiver() uint64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MessageSend) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageSend) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageSend)(nil), "pb.MessageSend")
}

func init() { proto.RegisterFile("message_send.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0x6e, 0x84, 0x30,
	0x10, 0x45, 0x65, 0x42, 0x80, 0x0c, 0xd0, 0x4c, 0x11, 0x59, 0x49, 0x11, 0x94, 0x34, 0x54, 0x69,
	0x72, 0x8a, 0x14, 0x69, 0xc8, 0xf6, 0x68, 0xc1, 0x23, 0xe4, 0x62, 0x8d, 0x65, 0x5b, 0x48, 0x5c,
	0x78, 0xcf, 0xb1, 0x62, 0x8c, 0xbb, 0xf9, 0xef, 0xeb, 0x3f, 0xd9, 0x80, 0x37, 0xf2, 0xfe, 0xba,
	0xd0, 0xe8, 0xc9, 0xa8, 0x6f, 0xeb, 0xd6, 0xb0, 0x62, 0x66, 0xa7, 0xcf, 0xbb, 0x80, 0xfa, 0x2f,
	0x56, 0xff, 0x64, 0x14, 0xbe, 0xc3, 0x8b, 0xa2, 0x4d, 0xcf, 0x34, 0x6a, 0x25, 0x45, 0x27, 0xfa,
	0x7c, 0xa8, 0x22, 0xf8, 0x55, 0xf8, 0x01, 0xf5, 0x59, 0x86, 0xdd, 0x92, 0xcc, 0x3a, 0xd1, 0xb7,
	0x03, 0x44, 0x74, 0xd9, 0x2d, 0xe1, 0x2b, 0x14, 0x87, 0x9f, 0x9c, 0x7c, 0xe2, 0xe9, 0x99, 0x10,
	0x21, 0xf7, 0x7a, 0x31, 0x32, 0x67, 0xca, 0x37, 0x7e, 0x41, 0xeb, 0x68, 0x26, 0xbd, 0x91, 0x8b,
	0xba, 0x67, 0xd6, 0x35, 0x09, 0xb2, 0xf0, 0x0d, 0xaa, 0x94, 0x65, 0x11, 0x5f, 0x93, 0xf2, 0x21,
	0xe5, 0x5d, 0xc9, 0x3b, 0xbe, 0x51, 0x42, 0x39, 0xaf, 0x26, 0x90, 0x09, 0xb2, 0xea, 0x44, 0xdf,
	0x0c, 0x29, 0x4e, 0x05, 0xff, 0xf9, 0xe7, 0x11, 0x00, 0x00, 0xff, 0xff, 0x91, 0x60, 0x7e, 0x98,
	0x09, 0x01, 0x00, 0x00,
}
