// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_ack.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message_ack.proto

It has these top-level messages:
	MessageACK
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 投递消息回执 type:6
type MessageACK struct {
	DeveiceId uint64 `protobuf:"varint,1,opt,name=deveice_id,json=deveiceId" json:"deveice_id,omitempty"`
	UserId    uint64 `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SnAck     uint64 `protobuf:"varint,3,opt,name=sn_ack,json=snAck" json:"sn_ack,omitempty"`
}

func (m *MessageACK) Reset()                    { *m = MessageACK{} }
func (m *MessageACK) String() string            { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()               {}
func (*MessageACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageACK) GetDeveiceId() uint64 {
	if m != nil {
		return m.DeveiceId
	}
	return 0
}

func (m *MessageACK) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageACK) GetSnAck() uint64 {
	if m != nil {
		return m.SnAck
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
}

func init() { proto.RegisterFile("message_ack.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0x8a, 0xe6, 0xe2, 0xf2, 0x85, 0x48, 0x38, 0x3a, 0x7b, 0x0b, 0xc9, 0x72, 0x71, 0xa5,
	0xa4, 0x96, 0xa5, 0x66, 0x26, 0xa7, 0xc6, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04,
	0x71, 0x42, 0x45, 0x3c, 0x53, 0x84, 0xc4, 0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0x40, 0x72, 0x4c,
	0x60, 0x39, 0x36, 0x10, 0xd7, 0x33, 0x45, 0x48, 0x94, 0x8b, 0xad, 0x38, 0x0f, 0x64, 0xb2, 0x04,
	0x33, 0x58, 0x9c, 0xb5, 0x38, 0xcf, 0x31, 0x39, 0x3b, 0x89, 0x0d, 0x6c, 0x8f, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x59, 0x14, 0xde, 0x64, 0x7c, 0x00, 0x00, 0x00,
}
