// Code generated by protoc-gen-go. DO NOT EDIT.
// source: online.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	online.proto

It has these top-level messages:
	OnLine
*/
package pb

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

var online OnLine

// 设备上线 type:1
type OnLine struct {
	DeviceId uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token    string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	LocalSn  uint64 `protobuf:"varint,4,opt,name=local_sn,json=localSn" json:"local_sn,omitempty"`
}

func (m *OnLine) Reset()                    { *m = OnLine{} }
func (m *OnLine) String() string            { return proto.CompactTextString(m) }
func (*OnLine) ProtoMessage()               {}
func (*OnLine) Descriptor() ([]byte, []int) { return online.fileDescriptor(), []int{0} }

func (m *OnLine) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *OnLine) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OnLine) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OnLine) GetLocalSn() uint64 {
	if m != nil {
		return m.LocalSn
	}
	return 0
}

func init() {
	proto.RegisterType((*OnLine)(nil), "pb.OnLine")
}

func init() { proto.RegisterFile("online.proto", online.fileDescriptor()) }

func (OnLine) fileDescriptor() []byte {
	return []byte{
		// 138 bytes of a gzipped FileDescriptorProto
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcf, 0xcb, 0xc9,
		0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe7, 0x62,
		0xf3, 0xcf, 0xf3, 0xc9, 0xcc, 0x4b, 0x15, 0x92, 0xe6, 0xe2, 0x4c, 0x49, 0x2d, 0xcb, 0x4c, 0x4e,
		0x8d, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0xe2, 0x80, 0x08, 0x78, 0xa6, 0x08,
		0x89, 0x73, 0xb1, 0x97, 0x16, 0xa7, 0x16, 0x81, 0xa4, 0x98, 0xc0, 0x52, 0x6c, 0x20, 0xae, 0x67,
		0x8a, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e, 0x76, 0x6a, 0x9e, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67,
		0x10, 0x84, 0x23, 0x24, 0xc9, 0xc5, 0x91, 0x93, 0x9f, 0x9c, 0x98, 0x13, 0x5f, 0x9c, 0x27, 0xc1,
		0x02, 0x56, 0xcf, 0x0e, 0xe6, 0x07, 0xe7, 0x25, 0xb1, 0x81, 0xed, 0x36, 0x06, 0x04, 0x00, 0x00,
		0xff, 0xff, 0x13, 0xe3, 0x5f, 0x46, 0x8b, 0x00, 0x00, 0x00,
	}
}
